apiVersion: v2
name: mongodb-operator
description: MongoDB Community Operator for MongoDB cluster management in OHS
type: application
version: 0.1.0
appVersion: "0.8.0"
home: https://github.com/mongodb/mongodb-kubernetes-operator
sources:
  - https://github.com/mongodb/mongodb-kubernetes-operator
maintainers:
  - name: Open Health Stack
    email: your.email@example.org
